coverage:
  if: true
codeToTestRatio:
  if: true
  code:
    - '**/*.go'
    - '!**/*_test.go'
  test:
    - '**/*_test.go'
testExecutionTime:
  if: true
diff:
  if: is_pull_request
  datastores:
    - artifact://${GITHUB_REPOSITORY}
push:
  if: is_default_branch
comment:
  if: is_pull_request
report:
  #if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
